services:
  server:
    container_name: server
    build:
      context: ./cloudberry-server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgres://postgres:Cloudberry@0@34.93.78.52:5432/cloudberry
      REDIS_URL: redis://34.14.214.83:6379
    command: sh -c "npm run prisma:migrate && npm run start:dev"
    env_file:
      - ./cloudberry-server/.env
    ports:
      - "4000:4000"
