services:
  db:
    container_name: zen-fashion-studio_db
    image: postgres:18
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    logging:
      driver: 'none'
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db-data:
    name: zen-fashion-studio_db-data
