services:
  db:
    container_name: postgresDB
    image: postgres:18
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    logging:
      driver: 'none'
    volumes:
      - db-data:/var/lib/postgresql

  redis:
    container_name: redis
    image: redis:7.4
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    logging:
      driver: "none"

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "npx prisma migrate dev && npm run start:dev"
    volumes:
      - ./:/app/
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 4000
#      TODO update database url for production secrets has been exposed
      DATABASE_URL: postgres://postgres:postgres@db:5432/cloudberry
      REDIS_URL: redis://redis:6379
    env_file:
      - ./.env
    ports:
      - "4000:4000"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    logging:
      driver: 'none'
    volumes:
      - ./cloudflared:/etc/cloudflared
    command: tunnel run
    depends_on:
      - server

volumes:
  db-data:
    name: cloudberry_db-data
  redis-data:
    name: cloudberry_redis-data
